## Capstone 2: Telco Customer Churn Prediction  

**1. Data Loading Summary**
- Loaded raw data
- Performed data analysis
- Data wrangling to clean the data
- Saved the cleaned data in csv format

**2. Exploratory Data Analysis (EDA)**
- Divide the features into difference categories
- For each feature alalyze the relationship with the target feature which is 'Churn' 

**3. Data Preprocessing**
- Create dummy variables for categorical features
- Normalize the numeric features
- Create testing set and training set

In [1]:
# Import libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
# Load the cleaned data

df = pd.read_csv('Excel_Files/Telco_customer_churn_cleaned.csv')
df.head()

,Unnamed: 0,index,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,0,0,1,0,1,0,0,1,...,1,1,1,1,0,1,0,29.85,29.85,0
1,1,1,1,0,0,0,34,1,1,1,...,2,1,1,1,1,0,1,56.95,1889.50,0
2,2,2,1,0,0,0,2,1,1,1,...,1,1,1,1,0,1,1,53.85,108.15,1
3,3,3,1,0,0,0,45,0,0,1,...,2,2,1,1,1,0,2,42.30,1840.75,0
4,4,4,0,0,0,0,2,1,1,2,...,1,1,1,1,0,1,0,70.70,151.65,1

In [3]:
print(df.shape, end='\n\n\n')
print(df.info(), end='\n\n\n')
print(df.describe().T, end='\n\n\n')

(7032, 22)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        7032 non-null   int64
 1   index             7032 non-null   int64
 2   gender            7032 non-null   int64
 3   SeniorCitizen     7032 non-null   int64
 4   Partner           7032 non-null   int64
 5   Dependents        7032 non-null   int64
 6   tenure            7032 non-null   int64
 7   PhoneService      7032 non-null   int64
 8   MultipleLines     7032 non-null   int64
 9   InternetService   7032 non-null   int64
 10  OnlineSecurity    7032 non-null   int64
 11  OnlineBackup      7032 non-null   int64
 12  DeviceProtection  7032 non-null   int64
 13  TechSupport       7032 non-null   int64
 14  StreamingTV       7032 non-null   int64
 15  StreamingMovies   7032 non-null   int64
 16  Contract          7032 non-null   int64
 17  PaperlessBilling  7032 non-null   int64
 18  PaymentMethod     7032 non-null   int64
 19  MonthlyCharges    7032 non-null   float64
 20  TotalCharges      7032 non-null   float64
 21  Churn             7032 non-null   int64
dtypes: float64(2), int64(20)
memory usage: 1.2 MB
None


                   count         mean          std    min        25%  \
Unnamed: 0        7032.0  3515.500000  2030.107879   0.00  1757.7500
index             7032.0  3521.562144  2032.832448   0.00  1762.7500
gender            7032.0     0.504693     0.500014   0.00     0.0000
SeniorCitizen     7032.0     0.162400     0.368844   0.00     0.0000
Partner           7032.0     0.482509     0.499729   0.00     0.0000
Dependents        7032.0     0.298493     0.457629   0.00     0.0000
tenure            7032.0    32.421786    24.545260   1.00     9.0000
PhoneService      7032.0     0.903299     0.295571   0.00     1.0000
MultipleLines     7032.0     1.325228     0.642585   0.00     1.0000
InternetService   7032.0     1.224118     0.778643   0.00     1.0000
OnlineSecurity    7032.0     1.070392     0.705562   0.00     1.0000
OnlineBackup      7032.0     1.128697     0.737917   0.00     1.0000
DeviceProtection  7032.0     1.127702     0.737415   0.00     1.0000
TechSupport       7032.0     1.073948     0.707715   0.00     1.0000
StreamingTV       7032.0     1.168231     0.756518   0.00     1.0000
StreamingMovies   7032.0     1.172213     0.758252   0.00     1.0000
Contract          7032.0     0.688567     0.832934   0.00     0.0000
PaperlessBilling  7032.0     0.592719     0.491363   0.00     0.0000
PaymentMethod     7032.0     1.315557     1.149523   0.00     0.0000
MonthlyCharges    7032.0    64.798208    30.085974  18.25    35.5875
TotalCharges      7032.0  2283.300441  2266.771362  18.80   401.4500
Churn             7032.0     0.265785     0.441782   0.00     0.0000

                       50%        75%      max
Unnamed: 0        3515.500  5273.2500  7031.00
index             3521.500  5282.2500  7042.00
gender               1.000     1.0000     1.00
SeniorCitizen        0.000     0.0000     1.00
Partner              0.000     1.0000     1.00
Dependents           0.000     1.0000     1.00
tenure              29.000    55.0000    72.00
PhoneService         1.000     1.0000     1.00
MultipleLines        1.000     2.0000     2.00
InternetService      1.000     2.0000     2.00
OnlineSecurity       1.000     2.0000     2.00
OnlineBackup         1.000     2.0000     2.00
DeviceProtection     1.000     2.0000     2.00
TechSupport          1.000     2.0000     2.00
StreamingTV          1.000     2.0000     2.00
StreamingMovies      1.000     2.0000     2.00
Contract             0.000     1.0000     2.00
PaperlessBilling     1.000     1.0000     1.00
PaymentMethod        1.000     2.0000     3.00
MonthlyCharges      70.350    89.8625   118.75
TotalCharges      1397.475  3794.7375  8684.80
Churn                0.000     1.0000     1.00

In [4]:
# Create new dataframe column with original labels instead of numbers
df1 = df.copy()

df1['gender'].replace(to_replace=0, value='Female', inplace=True)
df1['gender'].replace(to_replace=1, value='Male', inplace=True)

df1['Partner'].replace(to_replace=0, value='No', inplace=True)
df1['Partner'].replace(to_replace=1, value='Yes', inplace=True)

df1['Dependents'].replace(to_replace=0, value='No', inplace=True)
df1['Dependents'].replace(to_replace=1, value='Yes', inplace=True)

df1['PhoneService'].replace(to_replace=0, value='No', inplace=True)
df1['PhoneService'].replace(to_replace=1, value='Yes', inplace=True)

df1['MultipleLines'].replace(to_replace=0, value='No phone service', inplace=True)
df1['MultipleLines'].replace(to_replace=1, value='No', inplace=True)
df1['MultipleLines'].replace(to_replace=2, value='Yes', inplace=True)

df1['InternetService'].replace(to_replace=0, value='No', inplace=True)
df1['InternetService'].replace(to_replace=1, value='DSL', inplace=True)
df1['InternetService'].replace(to_replace=2, value='Fiber optic', inplace=True)

df1['OnlineSecurity'].replace(to_replace=0, value='No internet service', inplace=True)
df1['OnlineSecurity'].replace(to_replace=1, value='No', inplace=True)
df1['OnlineSecurity'].replace(to_replace=2, value='Yes', inplace=True)

df1['OnlineBackup'].replace(to_replace=0, value='No internet service', inplace=True)
df1['OnlineBackup'].replace(to_replace=1, value='No', inplace=True)
df1['OnlineBackup'].replace(to_replace=2, value='Yes', inplace=True)

df1['DeviceProtection'].replace(to_replace=0, value='No internet service', inplace=True)
df1['DeviceProtection'].replace(to_replace=1, value='No', inplace=True)
df1['DeviceProtection'].replace(to_replace=2, value='Yes', inplace=True)

df1['TechSupport'].replace(to_replace=0, value='No internet service', inplace=True)
df1['TechSupport'].replace(to_replace=1, value='No', inplace=True)
df1['TechSupport'].replace(to_replace=2, value='Yes', inplace=True)

df1['StreamingTV'].replace(to_replace=0, value='No internet service', inplace=True)
df1['StreamingTV'].replace(to_replace=1, value='No', inplace=True)
df1['StreamingTV'].replace(to_replace=2, value='Yes', inplace=True)

df1['StreamingMovies'].replace(to_replace=0, value='No internet service', inplace=True)
df1['StreamingMovies'].replace(to_replace=1, value='No', inplace=True)
df1['StreamingMovies'].replace(to_replace=2, value='Yes', inplace=True)

df1['Contract'].replace(to_replace=0, value='Month-to-month', inplace=True)
df1['Contract'].replace(to_replace=1, value='One year', inplace=True)
df1['Contract'].replace(to_replace=2, value='Two year', inplace=True)

df1['PaperlessBilling'].replace(to_replace=0, value='No', inplace=True)
df1['PaperlessBilling'].replace(to_replace=1, value='Yes', inplace=True)

df1['PaymentMethod'].replace(to_replace=0, value='Electronic check', inplace=True)
df1['PaymentMethod'].replace(to_replace=1, value='Mailed check', inplace=True)
df1['PaymentMethod'].replace(to_replace=2, value='Bank transfer (automatic)', inplace=True)
df1['PaymentMethod'].replace(to_replace=3, value='Credit card (automatic)', inplace=True)

df1['Churn'].replace(to_replace=0, value='No', inplace=True)
df1['Churn'].replace(to_replace=1, value='Yes', inplace=True)

In [5]:
print(df1.shape, end='\n\n\n')
print(df1.info(), end='\n\n\n')
print(df1.describe().T, end='\n\n\n')

(7032, 22)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        7032 non-null   int64
 1   index             7032 non-null   int64
 2   gender            7032 non-null   object
 3   SeniorCitizen     7032 non-null   int64
 4   Partner           7032 non-null   object
 5   Dependents        7032 non-null   object
 6   tenure            7032 non-null   int64
 7   PhoneService      7032 non-null   object
 8   MultipleLines     7032 non-null   object
 9   InternetService   7032 non-null   object
 10  OnlineSecurity    7032 non-null   object
 11  OnlineBackup      7032 non-null   object
 12  DeviceProtection  7032 non-null   object
 13  TechSupport       7032 non-null   object
 14  StreamingTV       7032 non-null   object
 15  StreamingMovies   7032 non-null   object
 16  Contract          7032 non-null   object
 17  PaperlessBilling  7032 non-null   object
 18  PaymentMethod     7032 non-null   object
 19  MonthlyCharges    7032 non-null   float64
 20  TotalCharges      7032 non-null   float64
 21  Churn             7032 non-null   object
dtypes: float64(2), int64(4), object(16)
memory usage: 1.2+ MB
None


                 count         mean          std    min        25%       50%  \
Unnamed: 0      7032.0  3515.500000  2030.107879   0.00  1757.7500  3515.500
index           7032.0  3521.562144  2032.832448   0.00  1762.7500  3521.500
SeniorCitizen   7032.0     0.162400     0.368844   0.00     0.0000     0.000
tenure          7032.0    32.421786    24.545260   1.00     9.0000    29.000
MonthlyCharges  7032.0    64.798208    30.085974  18.25    35.5875    70.350
TotalCharges    7032.0  2283.300441  2266.771362  18.80   401.4500  1397.475

                      75%      max
Unnamed: 0      5273.2500  7031.00
index           5282.2500  7042.00
SeniorCitizen      0.0000     1.00
tenure            55.0000    72.00
MonthlyCharges    89.8625   118.75
TotalCharges    3794.7375  8684.80

In [6]:
df1.columns

Index(['Unnamed: 0', 'index', 'gender', 'SeniorCitizen', 'Partner',
       'Dependents', 'tenure', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges',
       'Churn'],
      dtype='object')

In [7]:
df_categorical = df1.loc[:, ['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod', 'Churn']]

df_numerical = df1.loc[:, ['tenure', 'MonthlyCharges','TotalCharges' ]]

print(df_categorical.head(), end='\n\n\n')

print(df_numerical.head(), end='\n\n\n')

   gender  SeniorCitizen Partner Dependents PhoneService     MultipleLines  \
0  Female              0     Yes         No           No  No phone service
1    Male              0      No         No          Yes                No
2    Male              0      No         No          Yes                No
3    Male              0      No         No           No  No phone service
4  Female              0      No         No          Yes                No

  InternetService OnlineSecurity OnlineBackup DeviceProtection TechSupport  \
0             DSL             No          Yes               No          No
1             DSL            Yes           No              Yes          No
2             DSL            Yes          Yes               No          No
3             DSL            Yes           No              Yes         Yes
4     Fiber optic             No           No               No          No

  StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No              No  Month-to-month              Yes
1          No              No        One year               No
2          No              No  Month-to-month              Yes
3          No              No        One year               No
4          No              No  Month-to-month              Yes

               PaymentMethod Churn
0           Electronic check    No
1               Mailed check    No
2               Mailed check   Yes
3  Bank transfer (automatic)    No
4           Electronic check   Yes


   tenure  MonthlyCharges  TotalCharges
0       1           29.85         29.85
1      34           56.95       1889.50
2       2           53.85        108.15
3      45           42.30       1840.75
4       2           70.70        151.65

In [8]:
# Print shape of categorical and numerical dataframes

print(df_categorical.shape, end='\n\n\n')

print(df_numerical.shape, end='\n\n\n')

(7032, 17)


(7032, 3)

In [9]:
#Generate dummies for categorical columns only

df_dummy_cat = pd.get_dummies(df_categorical.astype('str'), drop_first = True)

df_dummy_cat.head()

,gender_Male,SeniorCitizen_1,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,OnlineSecurity_No internet service,...,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Churn_Yes
0,0,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
1,1,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
2,1,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,1
3,1,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,1,0,1,0,1

In [10]:
#Print shape of the dataframe after converting to dummies

print(df_dummy_cat.shape, end='\n\n\n')

(7032, 28)

In [11]:
# Merge the dummies dataframe with numerical dataframe

df_final = pd.concat([df_dummy_cat, df_numerical], axis = 1)

df_final.head()

,gender_Male,SeniorCitizen_1,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,OnlineSecurity_No internet service,...,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Churn_Yes,tenure,MonthlyCharges,TotalCharges
0,0,0,1,0,0,1,0,0,0,0,...,0,0,1,0,1,0,0,1,29.85,29.85
1,1,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,1,0,34,56.95,1889.50
2,1,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,1,1,2,53.85,108.15
3,1,0,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,45,42.30,1840.75
4,0,0,0,0,1,0,0,1,0,0,...,0,0,1,0,1,0,1,2,70.70,151.65

In [12]:
# Split the data into training set and testing set

X = df_final.drop(['Churn_Yes'], axis = 1)
y = df_final['Churn_Yes']

X_train, X_test, y_train, y_test  = train_test_split(X, y, test_size = 0.3, random_state = 100, stratify = y)

In [13]:
print("The number of rows and columns in X_train:", X_train.shape, end='\n\n')
print("The number of rows and columns in X_test:", X_test.shape, end='\n\n')
print("The number of rows and columns in y_train:", y_train.shape, end='\n\n')
print("The number of rows and columns in y_test:", y_test.shape, end='\n\n')

The number of rows and columns in X_train: (4922, 30)

The number of rows and columns in X_test: (2110, 30)

The number of rows and columns in y_train: (4922,)

The number of rows and columns in y_test: (2110,)

In [14]:
# Check to verify if the percentage of Churn customers is preserved in testing and training sets

print("Churn percentage in all data:", np.sum(y)*100/len(y), end='\n\n')
print("Churn percentage in training set:", np.sum(y_train)*100/len(y_train), end='\n\n')
print("Churn percentage in training set:", np.sum(y_test)*100/len(y_test), end='\n\n')

Churn percentage in all data: 26.57849829351536

Churn percentage in training set: 26.57456318569687

Churn percentage in training set: 26.587677725118482

In [15]:
X_train.head()

,gender_Male,SeniorCitizen_1,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,OnlineSecurity_No internet service,...,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure,MonthlyCharges,TotalCharges
3355,0,1,0,0,1,0,1,0,0,0,...,1,0,0,0,1,0,0,64,74.65,4869.35
113,0,1,1,0,1,0,1,1,0,0,...,0,0,0,1,0,1,0,37,76.50,2868.15
4298,0,0,1,0,1,0,0,0,1,1,...,0,0,1,1,0,0,1,29,19.55,521.80
6839,1,0,0,1,1,0,1,0,0,0,...,0,0,1,0,0,0,0,66,65.70,4378.90
1931,0,0,1,0,1,0,0,0,0,0,...,0,1,0,1,0,0,0,51,60.50,3145.15

In [16]:
# Scale the numeric columns for the training and testing set

cols_num = ['tenure', 'MonthlyCharges', 'TotalCharges']
scaler = StandardScaler()
scaler.fit(X_train[cols_num])

X_train_cp = X_train.copy()
X_test_cp = X_test.copy()
X_train_cp[cols_num] = scaler.transform(X_train[cols_num])
X_test_cp[cols_num] = scaler.transform(X_test[cols_num])

In [17]:
X_train_cp.head()

,gender_Male,SeniorCitizen_1,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,OnlineSecurity_No internet service,...,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure,MonthlyCharges,TotalCharges
3355,0,1,0,0,1,0,1,0,0,0,...,1,0,0,0,1,0,0,1.291907,0.328946,1.145390
113,0,1,1,0,1,0,1,1,0,0,...,0,0,0,1,0,1,0,0.188749,0.390508,0.259427
4298,0,0,1,0,1,0,0,0,1,1,...,0,0,1,1,0,0,1,-0.138113,-1.504610,-0.779340
6839,1,0,0,1,1,0,1,0,0,0,...,0,0,1,0,0,0,0,1.373622,0.031118,0.928260
1931,0,0,1,0,1,0,0,0,0,0,...,0,1,0,1,0,0,0,0.760757,-0.141922,0.382059

In [18]:
X_test_cp.head()

,gender_Male,SeniorCitizen_1,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,OnlineSecurity_No internet service,...,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure,MonthlyCharges,TotalCharges
6932,0,0,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,-1.282128,-1.140228,-0.996847
6688,1,0,0,0,1,0,0,1,0,0,...,1,1,0,1,1,0,0,0.311322,0.826436,0.533911
5606,1,0,0,0,1,0,0,0,1,1,...,0,0,0,1,0,0,0,-1.282128,-1.482980,-1.001406
4105,0,0,0,0,1,0,1,1,0,0,...,1,0,0,1,0,0,0,1.087618,1.154213,1.479353
5345,0,0,0,1,1,0,0,1,0,0,...,1,0,0,1,0,1,0,-1.282128,0.818116,-0.970793

In [19]:
X_train = X_train_cp.copy()
X_test = X_test_cp.copy()

print(X_train.describe().T, end='\n\n\n')
print(X_test.describe().T, end='\n\n\n')

                                        count          mean       std  \
gender_Male                            4922.0  5.050792e-01  0.500025
SeniorCitizen_1                        4922.0  1.607070e-01  0.367298
Partner_Yes                            4922.0  4.813084e-01  0.499701
Dependents_Yes                         4922.0  2.956115e-01  0.456364
PhoneService_Yes                       4922.0  9.026818e-01  0.296421
MultipleLines_No phone service         4922.0  9.731816e-02  0.296421
MultipleLines_Yes                      4922.0  4.185291e-01  0.493368
InternetService_Fiber optic            4922.0  4.408777e-01  0.496543
InternetService_No                     4922.0  2.161723e-01  0.411675
OnlineSecurity_No internet service     4922.0  2.161723e-01  0.411675
OnlineSecurity_Yes                     4922.0  2.870784e-01  0.452444
OnlineBackup_No internet service       4922.0  2.161723e-01  0.411675
OnlineBackup_Yes                       4922.0  3.488419e-01  0.476652
DeviceProtection_No internet service   4922.0  2.161723e-01  0.411675
DeviceProtection_Yes                   4922.0  3.472166e-01  0.476134
TechSupport_No internet service        4922.0  2.161723e-01  0.411675
TechSupport_Yes                        4922.0  2.905323e-01  0.454054
StreamingTV_No internet service        4922.0  2.161723e-01  0.411675
StreamingTV_Yes                        4922.0  3.809427e-01  0.485668
StreamingMovies_No internet service    4922.0  2.161723e-01  0.411675
StreamingMovies_Yes                    4922.0  3.876473e-01  0.487263
Contract_One year                      4922.0  2.135311e-01  0.409841
Contract_Two year                      4922.0  2.391304e-01  0.426596
PaperlessBilling_Yes                   4922.0  5.956928e-01  0.490807
PaymentMethod_Credit card (automatic)  4922.0  2.086550e-01  0.406389
PaymentMethod_Electronic check         4922.0  3.419342e-01  0.474406
PaymentMethod_Mailed check             4922.0  2.277529e-01  0.419425
tenure                                 4922.0 -1.032178e-16  1.000102
MonthlyCharges                         4922.0 -1.573530e-16  1.000102
TotalCharges                           4922.0 -3.212023e-17  1.000102

                                            min       25%       50%       75%  \
gender_Male                            0.000000  0.000000  1.000000  1.000000
SeniorCitizen_1                        0.000000  0.000000  0.000000  0.000000
Partner_Yes                            0.000000  0.000000  0.000000  1.000000
Dependents_Yes                         0.000000  0.000000  0.000000  1.000000
PhoneService_Yes                       0.000000  1.000000  1.000000  1.000000
MultipleLines_No phone service         0.000000  0.000000  0.000000  0.000000
MultipleLines_Yes                      0.000000  0.000000  0.000000  1.000000
InternetService_Fiber optic            0.000000  0.000000  0.000000  1.000000
InternetService_No                     0.000000  0.000000  0.000000  0.000000
OnlineSecurity_No internet service     0.000000  0.000000  0.000000  0.000000
OnlineSecurity_Yes                     0.000000  0.000000  0.000000  1.000000
OnlineBackup_No internet service       0.000000  0.000000  0.000000  0.000000
OnlineBackup_Yes                       0.000000  0.000000  0.000000  1.000000
DeviceProtection_No internet service   0.000000  0.000000  0.000000  0.000000
DeviceProtection_Yes                   0.000000  0.000000  0.000000  1.000000
TechSupport_No internet service        0.000000  0.000000  0.000000  0.000000
TechSupport_Yes                        0.000000  0.000000  0.000000  1.000000
StreamingTV_No internet service        0.000000  0.000000  0.000000  0.000000
StreamingTV_Yes                        0.000000  0.000000  0.000000  1.000000
StreamingMovies_No internet service    0.000000  0.000000  0.000000  0.000000
StreamingMovies_Yes                    0.000000  0.000000  0.000000  1.000000
Contract_One year                      0.000000  0.000000  0.000000  0.000000
Contract_Two year                      0.000000  0.000000  0.000000  0.000000
PaperlessBilling_Yes                   0.000000  0.000000  1.000000  1.000000
PaymentMethod_Credit card (automatic)  0.000000  0.000000  0.000000  0.000000
PaymentMethod_Electronic check         0.000000  0.000000  0.000000  1.000000
PaymentMethod_Mailed check             0.000000  0.000000  0.000000  0.000000
tenure                                -1.282128 -0.955267 -0.138113  0.924188
MonthlyCharges                        -1.547870 -0.965524  0.185856  0.834755
TotalCharges                          -1.002004 -0.831752 -0.385799  0.666438

                                            max
gender_Male                            1.000000
SeniorCitizen_1                        1.000000
Partner_Yes                            1.000000
Dependents_Yes                         1.000000
PhoneService_Yes                       1.000000
MultipleLines_No phone service         1.000000
MultipleLines_Yes                      1.000000
InternetService_Fiber optic            1.000000
InternetService_No                     1.000000
OnlineSecurity_No internet service     1.000000
OnlineSecurity_Yes                     1.000000
OnlineBackup_No internet service       1.000000
OnlineBackup_Yes                       1.000000
DeviceProtection_No internet service   1.000000
DeviceProtection_Yes                   1.000000
TechSupport_No internet service        1.000000
TechSupport_Yes                        1.000000
StreamingTV_No internet service        1.000000
StreamingTV_Yes                        1.000000
StreamingMovies_No internet service    1.000000
StreamingMovies_Yes                    1.000000
Contract_One year                      1.000000
Contract_Two year                      1.000000
PaperlessBilling_Yes                   1.000000
PaymentMethod_Credit card (automatic)  1.000000
PaymentMethod_Electronic check         1.000000
PaymentMethod_Mailed check             1.000000
tenure                                 1.618768
MonthlyCharges                         1.793129
TotalCharges                           2.828044


                                        count      mean       std       min  \
gender_Male                            2110.0  0.503791  0.500104  0.000000
SeniorCitizen_1                        2110.0  0.166351  0.372483  0.000000
Partner_Yes                            2110.0  0.485308  0.499903  0.000000
Dependents_Yes                         2110.0  0.305213  0.460607  0.000000
PhoneService_Yes                       2110.0  0.904739  0.293644  0.000000
MultipleLines_No phone service         2110.0  0.095261  0.293644  0.000000
MultipleLines_Yes                      2110.0  0.429858  0.495173  0.000000
InternetService_Fiber optic            2110.0  0.438863  0.496366  0.000000
InternetService_No                     2110.0  0.216114  0.411690  0.000000
OnlineSecurity_No internet service     2110.0  0.216114  0.411690  0.000000
OnlineSecurity_Yes                     2110.0  0.285308  0.451668  0.000000
OnlineBackup_No internet service       2110.0  0.216114  0.411690  0.000000
OnlineBackup_Yes                       2110.0  0.335545  0.472293  0.000000
DeviceProtection_No internet service   2110.0  0.216114  0.411690  0.000000
DeviceProtection_Yes                   2110.0  0.336019  0.472457  0.000000
TechSupport_No internet service        2110.0  0.216114  0.411690  0.000000
TechSupport_Yes                        2110.0  0.289100  0.453452  0.000000
StreamingTV_No internet service        2110.0  0.216114  0.411690  0.000000
StreamingTV_Yes                        2110.0  0.392417  0.488405  0.000000
StreamingMovies_No internet service    2110.0  0.216114  0.411690  0.000000
StreamingMovies_Yes                    2110.0  0.390047  0.487876  0.000000
Contract_One year                      2110.0  0.199526  0.399739  0.000000
Contract_Two year                      2110.0  0.240758  0.427645  0.000000
PaperlessBilling_Yes                   2110.0  0.585782  0.492703  0.000000
PaymentMethod_Credit card (automatic)  2110.0  0.234123  0.423550  0.000000
PaymentMethod_Electronic check         2110.0  0.323223  0.467818  0.000000
PaymentMethod_Mailed check             2110.0  0.228910  0.420231  0.000000
tenure                                 2110.0  0.005645  1.009502 -1.282128
MonthlyCharges                         2110.0  0.003697  1.003882 -1.532895
TotalCharges                           2110.0  0.001682  1.011740 -1.002026

                                            25%       50%       75%       max
gender_Male                            0.000000  1.000000  1.000000  1.000000
SeniorCitizen_1                        0.000000  0.000000  0.000000  1.000000
Partner_Yes                            0.000000  0.000000  1.000000  1.000000
Dependents_Yes                         0.000000  0.000000  1.000000  1.000000
PhoneService_Yes                       1.000000  1.000000  1.000000  1.000000
MultipleLines_No phone service         0.000000  0.000000  0.000000  1.000000
MultipleLines_Yes                      0.000000  0.000000  1.000000  1.000000
InternetService_Fiber optic            0.000000  0.000000  1.000000  1.000000
InternetService_No                     0.000000  0.000000  0.000000  1.000000
OnlineSecurity_No internet service     0.000000  0.000000  0.000000  1.000000
OnlineSecurity_Yes                     0.000000  0.000000  1.000000  1.000000
OnlineBackup_No internet service       0.000000  0.000000  0.000000  1.000000
OnlineBackup_Yes                       0.000000  0.000000  1.000000  1.000000
DeviceProtection_No internet service   0.000000  0.000000  0.000000  1.000000
DeviceProtection_Yes                   0.000000  0.000000  1.000000  1.000000
TechSupport_No internet service        0.000000  0.000000  0.000000  1.000000
TechSupport_Yes                        0.000000  0.000000  1.000000  1.000000
StreamingTV_No internet service        0.000000  0.000000  0.000000  1.000000
StreamingTV_Yes                        0.000000  0.000000  1.000000  1.000000
StreamingMovies_No internet service    0.000000  0.000000  0.000000  1.000000
StreamingMovies_Yes                    0.000000  0.000000  1.000000  1.000000
Contract_One year                      0.000000  0.000000  0.000000  1.000000
Contract_Two year                      0.000000  0.000000  0.000000  1.000000
PaperlessBilling_Yes                   0.000000  1.000000  1.000000  1.000000
PaymentMethod_Credit card (automatic)  0.000000  0.000000  0.000000  1.000000
PaymentMethod_Electronic check         0.000000  0.000000  1.000000  1.000000
PaymentMethod_Mailed check             0.000000  0.000000  0.000000  1.000000
tenure                                -0.985910 -0.138113  0.965045  1.618768
MonthlyCharges                        -0.976755  0.185856  0.836419  1.796457
TotalCharges                          -0.834652 -0.402257  0.675508  2.834552